### ISSUE TITLE
OutboundCall crashed! but probably should hangup gracefully.

### ISSUE THREAD

**Issue by mstate** [adhearsion/adhearsion#585] opened 2015-09-22 00:05 UTC
Just had a weird (repeatable) crash with Adhearsion 2.6.2 on Freeswitch 1.6.  When I call a real user who is setup on the local freeswitch, but not currently registered, mod_rayo can't seem to find the command and sends an error modification with a hangup instruction.  This causes adhearsion to throw an exception rather than following the hangup directive in the iq message.

Here are the relevant lines from the Freeswitch debug:

```
2015-09-20 18:17:11.096890 [NOTICE] switch_ivr_originate.c:2739 Cannot create outgoing channel of type [error] cause: [USER_NOT_REGISTERED] 
2015-09-20 18:17:11.096890 [DEBUG] switch_ivr_originate.c:3727 Originate Resulted in Error Cause: 606 [USER_NOT_REGISTERED] 
2015-09-20 18:17:11.156887 [DEBUG] mod_rayo.c:723 127.0.0.1, looking for SERVER::set:urn:xmpp:rayo:1:hangup command 
2015-09-20 18:17:11.156887 [DEBUG] mod_rayo.c:1817 modus_adhearsion@127.0.0.1/mikes-retina-macbook.local-84792, no handler function for command to 127.0.0.1 
2015-09-20 18:17:11.156887 [DEBUG] mod_rayo.c:1819 Deliver 127.0.0.1 => modus_adhearsion@127.0.0.1/mikes-retina-macbook.local-84792 <iq type='error' to='modus_adhearsion@127.0.0.1/mikes-retina-macbook.local-84792' id='1924141e-1bbf-4d57-ba37-009bd9bba3f8' from='127.0.0.1'><hangup xmlns='urn:xmpp:rayo:1'/><error type='modify'><feature-not-implemented xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/></error></iq> 
```

The exception on Adhearsion is: 
```
[2015-09-20 02:23:54.299] ERROR Celluloid: Adhearsion::OutboundCall crashed! 
Adhearsion::Call::Hangup: Adhearsion::Call::Hangup 
 /home/modus/apps/modus_surveyor/shared/bundle/ruby/2.2.0/bundler/gems/adhearsion-d80c2e832306/lib/adhearsion/call.rb:461:in `block in write_and_await_response' 
 /home/modus/apps/modus_surveyor/shared/bundle/ruby/2.2.0/bundler/gems/adhearsion-d80c2e832306/lib/adhearsion/call.rb:472:in `[]' 
 /home/modus/apps/modus_surveyor/shared/bundle/ruby/2.2.0/bundler/gems/adhearsion-d80c2e832306/lib/adhearsion/call.rb:472:in `write_and_await_response' 
 /home/modus/apps/modus_surveyor/shared/bundle/ruby/2.2.0/bundler/gems/adhearsion-d80c2e832306/lib/adhearsion/outbound_call.rb:96:in `dial'
```
Since mod_rayo is sending a hangup directive in it's iq message, shouldn't adhearsion hangup rather than responding to the mod_rayo feature-not-implemented message?

**Comment by benlangfeld** [comment] 2015-09-22 10:35
The `<hangup/>` in the response from mod_rayo is simply a reflection of the executed IQ set, not any indication that hangup has happened. I think this might be a mod_rayo bug, but you need to provide a full wire log for me to be sure.

**Comment by mstate** [comment] 2015-09-22 12:24
I pasted the section of the freeswitch log (started just before I initiated the calls) on http://pastebin.com/kiBGreZK.  I wasn't sure if that's what you meant by wire log.  If theres any other info you need, please let me know.

**Comment by mstate** [comment] 2015-09-22 14:12
Just received a response on Adhearsion's IRC from Chris Rienzo regarding mod_rayo actions that led to this call crash.
His comment was:
> ok, i looked at your debug log.  looks like mod_rayo is sending <end> event back to ahn before telling ahn that the call was created.  Things get a little confused on the ahn side then. 
> i can try to make it more sane in mod_rayo

**Comment by benlangfeld** [comment] 2015-09-22 14:58
I'm not actually convinced that's correct, @mstate. What I see is the stanzas being delivered in the correct order:

```
fe03e6d4-1874-4958-9aee-05f88b5042cc 2015-09-21 11:36:11.576838 [DEBUG] xmpp_streams.c:190 modus_adhearsion@127.0.0.1/mikes-retina-macbook.local-90514, 127.0.0.1:36332, c2s_in SEND <iq from=127.0.0.1 to=modus_adhearsion@127.0.0.1/mikes-retina-macbook.local-90514 id=e9949ae0-db52-4b3e-a200-ea124556d020 type=result><ref xmlns=urn:xmpp:rayo:1 uri=xmpp:6f8c6b22-7632-4f30-bdb0-602662cabbdc@127.0.0.1/></iq>
fe03e6d4-1874-4958-9aee-05f88b5042cc 2015-09-21 11:36:11.576838 [DEBUG] xmpp_streams.c:190 modus_adhearsion@127.0.0.1/mikes-retina-macbook.local-90514, 127.0.0.1:36332, c2s_in SEND <presence from=6f8c6b22-7632-4f30-bdb0-602662cabbdc@127.0.0.1 to=modus_adhearsion@127.0.0.1/mikes-retina-macbook.local-90514 type=unavailable><end xmlns=urn:xmpp:rayo:1><error platform-code=20/></end><delay xmlns=urn:xmpp:delay stamp=2015-09-21T15:36:11Z/></presence>
```

@crienzo Am I missing something?

@mstate Please provide Adhearsion logs at `TRACE` level.

**Comment by mstate** [comment] 2015-09-22 19:20
Okay, I've created a pastebin for the `TRACE` log at: http://pastebin.com/RSHWtibd
I also noticed that with a single call, the issue sometimes does not happen (it usually does though).   When I start multiple calls (my test runs 20), I always get the exception. I hope that helps.

**Comment by benlangfeld** [comment] 2015-12-07 14:18
Indeed @crienzo was correct:

```
[2015-09-22 15:06:48.881] TRACE Punchblock::Connection::XMPP: SENDING: (/Users/mike/.rvm/gems/ruby-2.2.2@modus_surveyor/gems/blather-1.1.4/lib/blather/client/client.rb:153:in `write') <iq type="set" to="127.0.0.1" id="2d35c2e9-897f-42a7-9ccc-7e76b421e5b6">
  <dial xmlns="urn:xmpp:rayo:1" to="user/star6" from="4168850803" uri="xmpp:25b9d2b5-85c5-4a37-bc26-51ff6399cff5@127.0.0.1"/>
</iq>
[2015-09-22 15:06:48.924] TRACE Punchblock::Connection::XMPP: RECEIVING (presence) <presence from="25b9d2b5-85c5-4a37-bc26-51ff6399cff5@127.0.0.1" to="modus_adhearsion@127.0.0.1/mikes-retina-macbook.local-11096" type="unavailable">
  <end xmlns="urn:xmpp:rayo:1">
    <error platform-code="20"/>
  </end>
  <delay xmlns="urn:xmpp:delay" stamp="2015-09-22T19:06:20Z"/>
</presence>
```

This looks like a mod_rayo bug. I'm going to close this for now; if you can reproduce an issue once @crienzo says mod_rayo is fixed, then I'll re-open and investigate.

**Closed by benlangfeld** 2015-12-07 14:18 UTC
